/** Phase identifiers for the pipeline delivery flow. */
export type PhaseId =
  | 'phase-0-entrance'
  | 'phase-1-propose'
  | 'phase-2-apply'
  | 'phase-3-review'
  | 'phase-4-unit-tests'
  | 'phase-5-archive'
  | 'phase-6-merge-push';

/**
 * All phases in pipeline order.
 */
export const ALL_PHASES: PhaseId[] = [
  'phase-0-entrance',
  'phase-1-propose',
  'phase-2-apply',
  'phase-3-review',
  'phase-4-unit-tests',
  'phase-5-archive',
  'phase-6-merge-push',
];

/** Phase metadata. */
export interface PhaseMeta {
  id: PhaseId;
  label: string;
  description: string;
  /** Path to the skill SKILL.md relative to the skills directory */
  skillPath: string;
  /** Readable name for the phase. */
  skillName: string;
}

/**
 * Metadata for each pipeline phase.
 */
export const PHASE_META: Record<PhaseId, PhaseMeta> = {
  'phase-0-entrance': {
    id: 'phase-0-entrance',
    label: 'Phase0 — Entrance',
    description: '环境预检 + 持久化状态初始化 + 入口路由',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-1-propose': {
    id: 'phase-1-propose',
    label: 'Phase1 — Propose',
    description: '创建 change + 生成 proposal/design/specs/tasks',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-2-apply': {
    id: 'phase-2-apply',
    label: 'Phase2 — Apply',
    description: '获取 apply 指令 + 逐任务实现 + self-review',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-3-review': {
    id: 'phase-3-review',
    label: 'Phase3 — Review',
    description: '代码审查 + secret/convention/correctness/security/perf',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-4-unit-tests': {
    id: 'phase-4-unit-tests',
    label: 'Phase4 — Unit Tests',
    description: '单元测试门禁',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-5-archive': {
    id: 'phase-5-archive',
    label: 'Phase5 — Archive',
    description: '测试结果门禁 + verify + 提案归档',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-6-merge-push': {
    id: 'phase-6-merge-push',
    label: 'Phase6 — Merge & Push',
    description: 'commit + source push + merge + post-merge verify + target push',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
};

/**
 * Status of a Phaseexecution.
 */
export type PhaseStatus = 'pass' | 'fail' | 'skipped' | 'error';

/**
 * Result of a single assertion.
 */
export interface AssertionResult {
  description: string;
  passed: boolean;
  detail?: string;
}

/**
 * Information about an artifact generated by a phase.
 */
export interface ArtifactInfo {
  path: string;
  type: 'file' | 'directory';
  exists: boolean;
  size?: number;
}

/**
 * Result of a single Phaseexecution.
 */
export interface AgentPhaseResult {
  phaseId: PhaseId;
  label: string;
  status: PhaseStatus;
  startedAt: string;
  durationMs: number;
  /** Summary of agent output/decisions */
  agentSummary: string;
  /** Structured assertions on Phaseoutput */
  assertions: AssertionResult[];
  /** Files/directories generated during this Phase*/
  artifacts: ArtifactInfo[];
  /** Errors encountered */
  errors?: string[];
  /** Phase-specific structured data */
  phaseData?: Record<string, unknown>;
}

/**
 * Configuration for a test scenario.
 */
export interface ScenarioConfig {
  /** Human-readable name */
  name: string;
  /** Sample project to use */
  sampleProject: string;
  /** Which phases to run */
  phases: PhaseId[];
  /** Tool adapter to use */
  toolId: 'claude' | 'cursor' | 'codex';
  /** Feature flags */
  features?: string[];
  /** OpenSpec implementation used inside the isolated environment. */
  openspecMode?: 'mock' | 'missing';
  /** The feature/change being implemented */
  changeName: string;
  /** Description of the feature for agent context */
  featureDescription: string;
}

/**
 * A test environment ready for pipeline execution.
 */
export interface TestEnvironment {
  rootDir: string;
  toolId: string;
  sampleProject: string;
  skillsRoot: string;
  skillRoot: string;
  commandsRoot: string;
  mockBinDir?: string;
  sourceBranch: string;
  targetBranch: string;
  remotePath: string;
  openspecMode: 'mock' | 'missing';
  isWorkTree: boolean;
  openspecAvailable: boolean;
  openspecVersion?: string;
  pipelineInitResult?: string;
  openspecInitResult?: string;
  cleanup: () => Promise<void>;
}

/**
 * Configuration for EnvironmentFactory.
 */
export interface EnvironmentConfig {
  sampleProject?: string;
  toolId?: 'claude' | 'cursor' | 'codex';
  features?: string[];
  changeName?: string;
  openspecMode?: 'mock' | 'missing';
}

/**
 * Full pipeline test report.
 */
export interface PipelineReport {
  meta: {
    scenarioName: string;
    sampleProject: string;
    toolId: string;
    changeName: string;
    sourceBranch: string;
    targetBranch: string;
    timestamp: string;
    durationMs: number;
    overallStatus: 'pass' | 'fail' | 'partial';
  };
  environment: {
    nodeVersion: string;
    openspecAvailable: boolean;
    openspecVersion?: string;
    openspecMode: 'mock' | 'missing';
    pipelineInitResult?: string;
  };
  phases: AgentPhaseResult[];
  summary: {
    totalPhases: number;
    passedPhases: number;
    failedPhases: number;
    skippedPhases: number;
    totalAssertions: number;
    passedAssertions: number;
    failedAssertions: number;
    overallScore: number;
    recommendations: string[];
  };
}
