/**
 * Phase identifiers for the pipeline delivery flow.
 */
export type PhaseId =
  | 'opsx-learn'
  | 'opsx-analysis'
  | 'opsx-design'
  | 'phase-0-entrance'
  | 'phase-1-propose'
  | 'phase-2-apply'
  | 'phase-3-review'
  | 'phase-4-archive'
  | 'phase-5-unit-tests'
  | 'phase-6-merge-push'
  | 'opsx-verify'
  | 'opsx-health';

/**
 * All phases in recommended order.
 */
export const ALL_PHASES: PhaseId[] = [
  'opsx-learn',
  'opsx-analysis',
  'opsx-design',
  'phase-0-entrance',
  'phase-1-propose',
  'phase-2-apply',
  'phase-3-review',
  'phase-4-archive',
  'phase-5-unit-tests',
  'phase-6-merge-push',
  'opsx-verify',
  'opsx-health',
];

/**
 * Phase metadata.
 */
export interface PhaseMeta {
  id: PhaseId;
  label: string;
  description: string;
  /** Path to the skill SKILL.md relative to .claude/skills/ */
  skillPath: string;
  /** Readable name for the phase */
  skillName: string;
}

/**
 * Metadata for each pipeline phase.
 */
export const PHASE_META: Record<PhaseId, PhaseMeta> = {
  'opsx-learn': {
    id: 'opsx-learn',
    label: 'Knowledge Learn',
    description: '沉淀项目知识到 .knowledge/ 知识库',
    skillPath: 'opsx-learn/SKILL.md',
    skillName: 'opsx-learn',
  },
  'opsx-analysis': {
    id: 'opsx-analysis',
    label: 'Requirement Analysis',
    description: '结构化需求分析：事实/推断/待确认',
    skillPath: 'opsx-analysis/SKILL.md',
    skillName: 'opsx-analysis',
  },
  'opsx-design': {
    id: 'opsx-design',
    label: 'Design Document',
    description: '设计文档 + 质量门禁 + 验证断言',
    skillPath: 'opsx-design/SKILL.md',
    skillName: 'opsx-design',
  },
  'phase-0-entrance': {
    id: 'phase-0-entrance',
    label: 'Phase 0 — Entrance',
    description: '环境预检 + Schema 检测 + 入口路由',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-1-propose': {
    id: 'phase-1-propose',
    label: 'Phase 1 — Propose',
    description: '创建 change + 生成 proposal/design/specs/tasks',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-2-apply': {
    id: 'phase-2-apply',
    label: 'Phase 2 — Apply',
    description: '获取 apply 指令 + 逐任务实现 + self-review',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-3-review': {
    id: 'phase-3-review',
    label: 'Phase 3 — Review',
    description: '代码审查 + secret/convention/correctness/security/perf',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-4-archive': {
    id: 'phase-4-archive',
    label: 'Phase 4 — Archive',
    description: '验证 + 文档归档 + knowledge 沉淀',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-5-unit-tests': {
    id: 'phase-5-unit-tests',
    label: 'Phase 5 — Unit Tests',
    description: '单元测试',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'phase-6-merge-push': {
    id: 'phase-6-merge-push',
    label: 'Phase 6 — Merge & Push',
    description: 'commit + push + merge',
    skillPath: 'opsx-dev-pipeline/SKILL.md',
    skillName: 'opsx-dev-pipeline',
  },
  'opsx-verify': {
    id: 'opsx-verify',
    label: 'Verification',
    description: '语言无关验证：冒烟/契约/回归',
    skillPath: 'opsx-verify/SKILL.md',
    skillName: 'opsx-verify',
  },
  'opsx-health': {
    id: 'opsx-health',
    label: 'Health Check',
    description: '知识库健康巡检 + P0-P3 建议',
    skillPath: 'opsx-health/SKILL.md',
    skillName: 'opsx-health',
  },
};

/**
 * Status of a phase execution.
 */
export type PhaseStatus = 'pass' | 'fail' | 'skipped' | 'error';

/**
 * Result of a single assertion.
 */
export interface AssertionResult {
  description: string;
  passed: boolean;
  detail?: string;
}

/**
 * Information about an artifact generated by a phase.
 */
export interface ArtifactInfo {
  path: string;
  type: 'file' | 'directory';
  exists: boolean;
  size?: number;
}

/**
 * Result of a single phase execution.
 */
export interface AgentPhaseResult {
  phaseId: PhaseId;
  label: string;
  status: PhaseStatus;
  startedAt: string;
  durationMs: number;
  /** Summary of agent output/decisions */
  agentSummary: string;
  /** Structured assertions on phase output */
  assertions: AssertionResult[];
  /** Files/directories generated during this phase */
  artifacts: ArtifactInfo[];
  /** Errors encountered */
  errors?: string[];
  /** Phase-specific structured data */
  phaseData?: Record<string, unknown>;
}

/**
 * Configuration for a test scenario.
 */
export interface ScenarioConfig {
  /** Human-readable name */
  name: string;
  /** Sample project to use */
  sampleProject: string;
  /** Which phases to run */
  phases: PhaseId[];
  /** Tool adapter to use */
  toolId: 'claude' | 'cursor' | 'codex' | 'generic';
  /** Feature flags */
  features?: string[];
  /** Custom schema config key */
  schemaConfig?: string;
  /** Skip pipeline init (for error recovery tests) */
  skipPipelineInit?: boolean;
  /** The feature/change being implemented */
  changeName: string;
  /** Description of the feature for agent context */
  featureDescription: string;
}

/**
 * A test environment ready for pipeline execution.
 */
export interface TestEnvironment {
  rootDir: string;
  toolId: string;
  sampleProject: string;
  skillsRoot: string;
  commandsRoot: string;
  knowledgeRoot: string;
  isWorkTree: boolean;
  openspecAvailable: boolean;
  openspecVersion?: string;
  pipelineInitResult?: string;
  openspecInitResult?: string;
  cleanup: () => Promise<void>;
}

/**
 * Configuration for EnvironmentFactory.
 */
export interface EnvironmentConfig {
  sampleProject?: string;
  toolId?: 'claude' | 'cursor' | 'codex' | 'generic';
  features?: string[];
  schemaConfig?: string;
  skipPipelineInit?: boolean;
}

/**
 * Full pipeline test report.
 */
export interface PipelineReport {
  meta: {
    scenarioName: string;
    sampleProject: string;
    toolId: string;
    schema: string;
    changeName: string;
    timestamp: string;
    durationMs: number;
    overallStatus: 'pass' | 'fail' | 'partial';
  };
  environment: {
    nodeVersion: string;
    openspecAvailable: boolean;
    openspecVersion?: string;
    pipelineInitResult?: string;
  };
  phases: AgentPhaseResult[];
  summary: {
    totalPhases: number;
    passedPhases: number;
    failedPhases: number;
    skippedPhases: number;
    totalAssertions: number;
    passedAssertions: number;
    failedAssertions: number;
    overallScore: number;
    recommendations: string[];
  };
}
