import type { PipelineReport, AgentPhaseResult } from '../harness/types.js';
import path from 'node:path';
import fs from 'fs-extra';

/**
 * Generate a human-readable Markdown report.
 */
export class MarkdownReporter {
  private outputDir: string;

  constructor(outputDir: string) {
    this.outputDir = outputDir;
  }

  async generate(report: PipelineReport): Promise<string> {
    const timestamp = formatTimestamp(new Date(report.meta.timestamp));
    const scenarioSlug = slugify(report.meta.scenarioName);
    const reportDir = path.join(this.outputDir, `${timestamp}-${scenarioSlug}`);
    await fs.ensureDir(reportDir);

    const content = this.renderMarkdown(report);
    const mdPath = path.join(reportDir, 'report.md');
    await fs.writeFile(mdPath, content, 'utf-8');

    return mdPath;
  }

  private renderMarkdown(report: PipelineReport): string {
    const lines: string[] = [];

    // Title & Meta
    lines.push(`# Pipeline Delivery Flow Test Report`);
    lines.push('');
    lines.push(`**Scenario**: ${report.meta.scenarioName}`);
    lines.push(`**Sample Project**: ${report.meta.sampleProject}`);
    lines.push(`**Change**: \`${report.meta.changeName}\``);
    lines.push(`**Source Branch**: \`${report.meta.sourceBranch}\``);
    lines.push(`**Target Branch**: \`${report.meta.targetBranch}\``);
    lines.push(`**Timestamp**: ${report.meta.timestamp}`);
    lines.push(`**Duration**: ${formatDuration(report.meta.durationMs)}`);
    lines.push(`**Overall Status**: ${statusBadge(report.meta.overallStatus)}`);
    lines.push('');

    // Environment
    lines.push('## Environment');
    lines.push('');
    lines.push(`| Property | Value |`);
    lines.push(`|----------|-------|`);
    lines.push(`| Node.js | ${report.environment.nodeVersion} |`);
    lines.push(
      `| OpenSpec Available | ${report.environment.openspecAvailable ? '✅ Yes' : '❌ No'} |`,
    );
    if (report.environment.openspecVersion) {
      lines.push(`| OpenSpec Version | \`${report.environment.openspecVersion}\` |`);
    }
    lines.push(`| OpenSpec Mode | ${report.environment.openspecMode} |`);
    lines.push('');

    // Summary
    lines.push('## Summary');
    lines.push('');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Total Phases | ${report.summary.totalPhases} |`);
    lines.push(`| Passed | ${report.summary.passedPhases} |`);
    lines.push(`| Failed | ${report.summary.failedPhases} |`);
    lines.push(`| Skipped | ${report.summary.skippedPhases} |`);
    lines.push(`| Total Assertions | ${report.summary.totalAssertions} |`);
    lines.push(`| Passed Assertions | ${report.summary.passedAssertions} |`);
    lines.push(`| Failed Assertions | ${report.summary.failedAssertions} |`);
    lines.push(`| **Overall Score** | **${report.summary.overallScore}/100** |`);
    lines.push('');

    // Phase-by-phase details
    lines.push('## Phase Details');
    lines.push('');

    for (const phase of report.phases) {
      lines.push(...this.renderPhase(phase));
    }

    // Recommendations
    if (report.summary.recommendations.length > 0) {
      lines.push('## Recommendations');
      lines.push('');
      for (const rec of report.summary.recommendations) {
        lines.push(`- ${rec}`);
      }
      lines.push('');
    }

    // Footer
    lines.push('---');
    lines.push(`*Report generated by opsx-dev-pipeline delivery flow test framework*`);

    return lines.join('\n');
  }

  private renderPhase(phase: AgentPhaseResult): string[] {
    const lines: string[] = [];

    lines.push(`### ${phase.label} ${statusBadge(phase.status)}`);
    lines.push('');
    lines.push(`- **Duration**: ${formatDuration(phase.durationMs)}`);
    lines.push(`- **Started**: ${phase.startedAt}`);
    lines.push('');
    lines.push(`**Execution Summary**: ${phase.agentSummary}`);
    lines.push('');

    // Errors
    if (phase.errors && phase.errors.length > 0) {
      lines.push('#### Errors');
      lines.push('');
      for (const err of phase.errors) {
        lines.push(`- ❌ ${err}`);
      }
      lines.push('');
    }

    // Assertions
    if (phase.assertions.length > 0) {
      lines.push('#### Assertions');
      lines.push('');
      lines.push('| Status | Description | Detail |');
      lines.push('|--------|-------------|--------|');
      for (const a of phase.assertions) {
        const icon = a.passed ? '✅' : '❌';
        const detail = a.detail || '—';
        lines.push(`| ${icon} | ${a.description} | ${detail} |`);
      }
      lines.push('');
    }

    // Artifacts
    if (phase.artifacts.length > 0) {
      lines.push('#### Artifacts');
      lines.push('');
      for (const a of phase.artifacts) {
        const icon = a.exists ? '📄' : '❌';
        const type = a.type === 'directory' ? ' (dir)' : '';
        lines.push(`- ${icon} \`${a.path}\`${type}`);
      }
      lines.push('');
    }

    return lines;
  }
}

function statusBadge(status: string): string {
  switch (status) {
    case 'pass':
      return '🟢 PASS';
    case 'fail':
      return '🔴 FAIL';
    case 'partial':
      return '🟡 PARTIAL';
    case 'error':
      return '💥 ERROR';
    case 'skipped':
      return '⚪ SKIPPED';
    default:
      return `\`${status}\``;
  }
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  const seconds = Math.floor(ms / 1000);
  if (seconds < 60) return `${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  return `${minutes}m ${remainingSeconds}s`;
}

function formatTimestamp(date: Date): string {
  return date.toISOString().replace(/:/g, '-').replace(/\..+/, '');
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}
