import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import {
  apiErrorSchema,
  apiSuccessSchema,
  endpointKey,
  endpointRegistry,
} from '../src/api/contracts/registry.js';

const serverRoot = fileURLToPath(new URL('..', import.meta.url));
const openApiPath = `${serverRoot}/docs/openapi.json`;
const frontendPath = `${serverRoot}/../metrics-website/lib/generated/api-contract.ts`;

function jsonSchema(schema: z.ZodType) {
  const result = z.toJSONSchema(schema, { io: 'input' }) as Record<string, unknown>;
  delete result.$schema;
  return result;
}

function parameters(schema: z.ZodType, location: 'path' | 'query') {
  const converted = jsonSchema(schema) as {
    properties?: Record<string, unknown>;
    required?: string[];
  };
  return Object.entries(converted.properties ?? {}).map(([name, property]) => ({
    name,
    in: location,
    required: location === 'path' || converted.required?.includes(name) || false,
    schema: property,
  }));
}

function openApiPathFor(expressPath: string) {
  return expressPath.replace(/:([A-Za-z0-9_]+)/g, '{$1}');
}

function buildOpenApi() {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const endpoint of endpointRegistry) {
    const path = openApiPathFor(endpoint.path);
    paths[path] ??= {};
    const requestSchema = jsonSchema(endpoint.body);
    paths[path][endpoint.method] = {
      operationId: endpointKey(endpoint).toLowerCase().replace(/[^a-z0-9]+/g, '_'),
      security:
        endpoint.auth === 'public'
          ? []
          : endpoint.auth === 'user'
            ? [{ bearerAuth: [] }]
            : [{ bearerAuth: [] }, { serviceKey: [] }],
      parameters: [
        ...parameters(endpoint.params, 'path'),
        ...parameters(endpoint.query, 'query'),
      ],
      ...(Object.keys((requestSchema as { properties?: object }).properties ?? {}).length
        ? {
            requestBody: {
              required: true,
              content: { 'application/json': { schema: requestSchema } },
            },
          }
        : {}),
      responses: Object.fromEntries([
        [
          String(endpoint.successStatus),
          {
            description: 'Success',
            content: { 'application/json': { schema: jsonSchema(apiSuccessSchema) } },
          },
        ],
        ...endpoint.errors.map((status) => [
          String(status),
          {
            description: 'Error',
            content: { 'application/json': { schema: jsonSchema(apiErrorSchema) } },
          },
        ]),
      ]),
    };
  }
  return {
    openapi: '3.1.0',
    info: { title: 'OpsFlow Metrics API', version: '1.0.0' },
    servers: [{ url: '/api/v1' }],
    components: {
      securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
        serviceKey: { type: 'apiKey', in: 'header', name: 'x-api-key' },
      },
    },
    paths,
  };
}

function buildFrontendTypes() {
  const keys = endpointRegistry.map(endpointKey);
  const metadata = Object.fromEntries(
    endpointRegistry.map((endpoint) => [
      endpointKey(endpoint),
      {
        method: endpoint.method.toUpperCase(),
        path: endpoint.path,
        auth: endpoint.auth,
        successStatus: endpoint.successStatus,
        errorStatuses: endpoint.errors,
      },
    ]),
  );
  return `// Generated by metrics-server/scripts/generate-api-contract.ts. Do not edit.\n\nexport type ApiEndpointKey = ${keys.map((key) => JSON.stringify(key)).join(' | ')};\n\nexport interface ApiResponsePayload<T> {\n  success?: boolean;\n  code?: string | number;\n  message?: string;\n  data?: T | null;\n  details?: unknown;\n  requestId?: string;\n}\n\nexport const apiEndpointMetadata = ${JSON.stringify(metadata, null, 2)} as const satisfies Record<ApiEndpointKey, { method: string; path: string; auth: 'public' | 'user' | 'admin'; successStatus: number; errorStatuses: readonly number[] }>;\n`;
}

const openApi = `${JSON.stringify(buildOpenApi(), null, 2)}\n`;
const frontendTypes = buildFrontendTypes();
const check = process.argv.includes('--check');
if (check) {
  const [existingOpenApi, existingFrontend] = await Promise.all([
    readFile(openApiPath, 'utf8'),
    readFile(frontendPath, 'utf8'),
  ]);
  if (existingOpenApi !== openApi || existingFrontend !== frontendTypes) {
    throw new Error('Generated API contract is stale; run npm run contract:generate');
  }
} else {
  await mkdir(fileURLToPath(new URL('../docs', import.meta.url)), { recursive: true });
  await mkdir(fileURLToPath(new URL('../../metrics-website/lib/generated', import.meta.url)), {
    recursive: true,
  });
  await Promise.all([
    writeFile(openApiPath, openApi),
    writeFile(frontendPath, frontendTypes),
  ]);
  process.stdout.write(`Generated ${endpointRegistry.length} API endpoint contracts\n`);
}
