import type { AssetDefinition } from './types.js';

export const assetManifest: AssetDefinition[] = [
  {
    id: 'common-readme',
    kind: 'template',
    scope: 'common',
    feature: 'base',
    source: 'templates/common/base/README.md.hbs',
    destination: 'README.md',
    writePolicy: { appendStrategy: 'simple' },
  },
  {
    id: 'common-gitignore',
    kind: 'static',
    scope: 'common',
    feature: 'base',
    source: 'templates/common/base/gitignore',
    destination: '.gitignore',
    writePolicy: { appendStrategy: 'none' },
  },
  {
    id: 'frontend-schema-bundle',
    kind: 'bundle',
    scope: 'common',
    feature: 'schema',
    stacks: ['frontend'],
    source: 'templates/common/schemas/frontend',
    destination: 'openspec/schemas/frontend',
    includeExtensions: ['.md', '.yaml', '.hbs'],
    templateFiles: [
      'schema.yaml.hbs',
      'proposal.md.hbs',
      'design.md.hbs',
      'spec.md.hbs',
      'tasks.md.hbs',
    ],
    excludePatterns: ['.gitkeep'],
    writePolicy: { appendStrategy: 'simple', appendExtensions: ['.md'] },
    bundleGatedFiles: [],
  },
  {
    id: 'backend-schema-bundle',
    kind: 'bundle',
    scope: 'common',
    feature: 'schema',
    stacks: ['backend'],
    source: 'templates/common/schemas/backend',
    destination: 'openspec/schemas/backend',
    includeExtensions: ['.md', '.yaml', '.hbs'],
    templateFiles: [
      'schema.yaml.hbs',
      'proposal.md.hbs',
      'design.md.hbs',
      'spec.md.hbs',
      'tasks.md.hbs',
    ],
    excludePatterns: ['.gitkeep'],
    writePolicy: { appendStrategy: 'simple', appendExtensions: ['.md'] },
    bundleGatedFiles: [],
  },
  {
    id: 'stack-config',
    kind: 'template',
    scope: 'common',
    feature: 'schema',
    source: 'templates/common/config/config.{{stack}}.yaml.hbs',
    destination: 'openspec/config.yaml',
    writePolicy: { appendStrategy: 'config-merge' },
  },
  {
    id: 'opsx-dev-pipeline-skill-bundle',
    kind: 'bundle',
    scope: 'common',
    feature: 'skills',
    source: 'templates/common/skills/opsx-dev-pipeline',
    destination: '{{skillsDir}}/opsx-dev-pipeline',
    includeExtensions: ['.md', '.hbs', '.mjs', '.yaml'],
    templateFiles: [
      'SKILL.md.hbs',
      'phase-0-entrance.md.hbs',
      'phase-1-propose.md.hbs',
      'phase-2-apply.md.hbs',
      'phase-3-review.md.hbs',
      'phase-4-unit-tests.md.hbs',
      'phase-5-archive.md.hbs',
      'phase-6-merge-push.md.hbs',
    ],
    excludePatterns: ['.gitkeep'],
    writePolicy: { appendStrategy: 'simple', appendExtensions: ['.md'] },
  },
  {
    id: 'grill-me-skill-bundle',
    kind: 'bundle',
    scope: 'common',
    feature: 'skills',
    source: 'templates/common/skills/grill-me',
    destination: '{{skillsDir}}/grill-me',
    includeExtensions: ['.md', '.yaml'],
    excludePatterns: ['.gitkeep'],
    writePolicy: { appendStrategy: 'simple', appendExtensions: ['.md'] },
  },
  {
    id: 'grilling-skill-bundle',
    kind: 'bundle',
    scope: 'common',
    feature: 'skills',
    source: 'templates/common/skills/grilling',
    destination: '{{skillsDir}}/grilling',
    includeExtensions: ['.md', '.yaml'],
    excludePatterns: ['.gitkeep'],
    writePolicy: { appendStrategy: 'simple', appendExtensions: ['.md'] },
  },
  {
    id: 'opsx-dev-pipeline-command',
    kind: 'template',
    scope: 'common',
    feature: 'commands',
    source: 'templates/common/commands/opsx-dev-pipeline.md.hbs',
    destination: '{{commandsDir}}/opsx-dev-pipeline.md',
    writePolicy: { appendStrategy: 'simple' },
  },
  {
    id: 'opsx-propose-command',
    kind: 'template',
    scope: 'common',
    feature: 'commands',
    source: 'templates/common/commands/opsx/propose.md.hbs',
    destination: '{{commandsDir}}/opsx/propose.md',
    writePolicy: { appendStrategy: 'simple', onConflict: { init: 'overwrite' } },
  },
  {
    id: 'opsx-apply-command',
    kind: 'template',
    scope: 'common',
    feature: 'commands',
    source: 'templates/common/commands/opsx/apply.md.hbs',
    destination: '{{commandsDir}}/opsx/apply.md',
    writePolicy: { appendStrategy: 'simple', onConflict: { init: 'overwrite' } },
  },
  {
    id: 'opsx-archive-command',
    kind: 'template',
    scope: 'common',
    feature: 'commands',
    source: 'templates/common/commands/opsx/archive.md.hbs',
    destination: '{{commandsDir}}/opsx/archive.md',
    writePolicy: { appendStrategy: 'simple', onConflict: { init: 'overwrite' } },
  },
  {
    id: 'opsx-verify-command',
    kind: 'template',
    scope: 'common',
    feature: 'commands',
    source: 'templates/common/commands/opsx/verify.md.hbs',
    destination: '{{commandsDir}}/opsx/verify.md',
    writePolicy: { appendStrategy: 'simple', onConflict: { init: 'overwrite' } },
  },
  {
    id: 'opsx-sync-command',
    kind: 'template',
    scope: 'common',
    feature: 'commands',
    source: 'templates/common/commands/opsx/sync.md.hbs',
    destination: '{{commandsDir}}/opsx/sync.md',
    writePolicy: { appendStrategy: 'simple', onConflict: { init: 'overwrite' } },
  },
  {
    id: 'opsx-explore-command',
    kind: 'template',
    scope: 'common',
    feature: 'commands',
    source: 'templates/common/commands/opsx/explore.md.hbs',
    destination: '{{commandsDir}}/opsx/explore.md',
    writePolicy: { appendStrategy: 'simple', onConflict: { init: 'overwrite' } },
  },
  {
    id: 'claude-docs',
    kind: 'template',
    scope: 'tool',
    feature: 'docs',
    tools: ['claude'],
    source: 'templates/tools/claude/overlay/CLAUDE.md.hbs',
    destination: 'CLAUDE.md',
    writePolicy: { appendStrategy: 'simple' },
  },
  {
    id: 'cursor-docs',
    kind: 'template',
    scope: 'tool',
    feature: 'docs',
    tools: ['cursor'],
    source: 'templates/tools/cursor/overlay/.cursor/rules/opsx-dev-pipeline.mdc.hbs',
    destination: '.cursor/rules/opsx-dev-pipeline.mdc',
    writePolicy: { appendStrategy: 'simple' },
  },
  {
    id: 'cursor-command-guide',
    kind: 'template',
    scope: 'tool',
    feature: 'commands',
    tools: ['cursor'],
    source: 'templates/tools/cursor/overlay/.cursor/commands/README.md.hbs',
    destination: '.cursor/commands/README.md',
    writePolicy: { appendStrategy: 'simple' },
  },
  {
    id: 'codex-docs',
    kind: 'template',
    scope: 'tool',
    feature: 'docs',
    tools: ['codex'],
    source: 'templates/tools/codex/overlay/.codex/prompts/opsx-dev-pipeline.md.hbs',
    destination: '.codex/prompts/opsx-dev-pipeline.md',
    writePolicy: { appendStrategy: 'simple' },
  },
  {
    id: 'codex-command-guide',
    kind: 'template',
    scope: 'tool',
    feature: 'commands',
    tools: ['codex'],
    source: 'templates/tools/codex/overlay/.codex/commands/README.md.hbs',
    destination: '.codex/commands/README.md',
    writePolicy: { appendStrategy: 'simple' },
  },
];
